log:
  level: info
  format: json
  logFile: "./logs/ValidationService.log"
  logFileMaxMb: 1
  logFileRotationCount: 30
  logFileRotationDays: 1
httpPort: 8080
mongo:
  url: mongodb://mongo
  db: validationService
  retryMilliseconds: 0
appd:
  appName: validationService
  tierName: transaction
  nodeName: transaction01
  initTimeout: 1000
  controller:
    host: somehost
    port: 443
    useSSL: true
    account: account
    accessKey: password
