log:
  level: info
  format: json
  logFile: ./logs/main.log
  logFileMaxMb: 1
  logRotatingPeriod: 1
  logRotatingCount: 30
  healthCheckLogFile: ./logs/health.log
  healthCheckLogRotatingPeriod: 10
  healthCheckLogRotatingCount: 2
  traceIdHeader: x-b3-traceid
httpPort: 8080
mongo:
  url: mongodb://mongo
  db: validationService
  retryMilliseconds: 0
entityService:
    entityServiceUrl: https://dev2.test-gsc.vfims.com/oidc/ds-entity-service
    entityServiceTimeout: 20
appd:
  appName: validationService
  tierName: transaction
  nodeName: transaction01
  initTimeout: 1000
  controller:
    host: somehost
    port: 443
    proxyHost:
    proxyPort:
    useSSL: true
    account: account
    accessKey: password
