log:
  level: info
  format: text
httpPort: 8080
mongo:
  url: mongodb://mongo
  db: validationService
appd:
  appName: validationService
  tierName: transaction
  nodeName: transaction01
  initTimeout: 1000
  controller:
    host: verifone-test.saas.appdynamics.com
    port: 443
    useSSL: true
    account: verifone-test
    accessKey: pagow299f851
