log:
  level: info
  format: json
  logFile: ./logs/main.log
  logFileMaxMb: 1
  logRotatingPeriod: 30
  logRotatingCount: 10
  healthCheckLogFile: ./logs/health.log
  healthCheckLogRotatingPeriod: 10
  healthCheckLogRotatingCount: 2
httpPort: 8080
mongo:
  url: mongodb://mongo
  db: validationService
  retryMilliseconds: 0
appd:
  appName: validationService
  tierName: transaction
  nodeName: transaction01
  initTimeout: 1000
  controller:
    host: somehost
    port: 443
    proxyHost:
    proxyPort:
    useSSL: true
    account: account
    accessKey: password
