version: '3'
services:
  app:
    build:
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/go/src/validation-service
    environment:
      - ENVIRONMENT=development
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4.1
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongo-data:/data/db
    command: mongod --logpath=/dev/null --quiet
volumes:
  mongo-data:
