version: '3'
services:
  app:
    build:
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - "3000:3000"
    volumes:
      - ./:/go/src/bitbucket.verifone.com/validation-service
    links:
      - mongo
    depends_on:
      - mongo
    env_file:
      - .env
    environment:
      - MONGO_URL=mongodb://mongo
      - LOG_FORMAT=text
      - LOG_LEVEL=trace
  mongo:
    image: mongo:4.2.2
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongo-data:/data/db
    command: mongod --logpath=/dev/null --quiet
volumes:
  mongo-data:
