FROM golang:1.13.14-buster

ENV CGO_ENABLED=1
ENV GOOS=linux
ENV GOARCH=amd64
ENV GOPATH /go
ENV HTTP_PORT=8080

RUN apt-get update && apt-get install -y --no-install-recommends g++ gcc libc6-dev curl && \
    rm -rf /var/lib/apt/lists/*

# Install Gin live reloading golang library
RUN go get github.com/codegangsta/gin

# Expose port 3000 to the host so we can access the gin proxy
EXPOSE 3000

WORKDIR /go/src/validation-service

COPY . .

HEALTHCHECK CMD curl --fail http://localhost:8080/healthCheck || exit 1

CMD gin --immediate --appPort $HTTP_PORT --bin validation-service run
