version: '3'
services:
  app:
    platform: linux/amd64  # Add this line
    build:
      dockerfile: Dockerfile.dev
      context: .
    ports:
      - "3000:3000"
      - "8080:8080"
    volumes:
      - ./:/go/src/validation-service
    environment:
      - ENVIRONMENT=development
      - HTTP_PORT=8080
      - CGO_ENABLED=1
      - GOOS=linux
      - GOARCH=amd64
    links:
      - mongo
    depends_on:
      - mongo
  mongo:
    image: mongo:4.4.1
    restart: always
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - mongo-data:/data/db
    command: mongod --logpath=/dev/null --quiet
volumes:
  mongo-data:
